## Deliverable 2. Create a Customer Travel Destinations Map.

In [22]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
# Import API key
from config import G_API_Key


# Configure gmaps API key
gmaps.configure(api_key=G_API_Key)

In [35]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv", index_col=False)

In [36]:
city_data_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Kapaa,US,22.0752,-159.3190,80.58,81,59,4.00,broken clouds
1,1,Punta Arenas,CL,-53.1500,-70.9167,42.12,93,100,6.93,light rain
2,2,Cape Town,ZA,-33.9258,18.4232,58.91,73,20,5.99,few clouds
3,3,Aksarka,RU,66.5606,67.7975,3.36,95,100,1.86,overcast clouds
4,4,Hobyo,SO,5.3505,48.5268,83.25,72,67,9.84,broken clouds
...,...,...,...,...,...,...,...,...,...,...
691,691,Mizdah,LY,31.4451,12.9801,55.94,56,54,7.14,broken clouds
692,692,Kysyl-Syr,RU,63.8986,122.7617,26.56,77,99,2.44,overcast clouds
693,693,Honningsvag,NO,70.9821,25.9704,38.95,87,100,16.11,light intensity drizzle
694,694,Takoradi,GH,4.8845,-1.7554,79.54,88,99,6.26,light rain
695,695,Floro,NO,61.5996,5.0328,46.36,76,17,8.05,few clouds

In [32]:
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Kapaa,US,22.0752,-159.3190,80.58,81,59,4.00,broken clouds
1,1,Punta Arenas,CL,-53.1500,-70.9167,42.12,93,100,6.93,light rain
2,2,Cape Town,ZA,-33.9258,18.4232,58.91,73,20,5.99,few clouds
3,3,Aksarka,RU,66.5606,67.7975,3.36,95,100,1.86,overcast clouds
4,4,Hobyo,SO,5.3505,48.5268,83.25,72,67,9.84,broken clouds

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip?")) 
max_temp = float(input("What is the maximum temperature you would like for your trip?"))

What is the minimum temperature you would like for your trip?75
What is the maximum temperature you would like for your trip?90

In [12]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Kapaa,US,22.0752,-159.3190,80.58,81,59,4.00,broken clouds
4,4,Hobyo,SO,5.3505,48.5268,83.25,72,67,9.84,broken clouds
10,10,Mabay,PH,6.0577,124.4666,84.15,76,64,2.77,moderate rain
11,11,Buctzotz,MX,21.2000,-88.7833,82.69,54,82,11.14,broken clouds
12,12,Rikitea,PF,-23.1203,-134.9692,75.33,77,100,15.55,moderate rain
20,20,Namatanai,PG,-3.6667,152.4333,85.69,62,90,5.95,overcast clouds
22,22,Butaritari,KI,3.0707,172.7902,81.52,77,54,13.91,broken clouds
23,23,Bajil,YE,15.0584,43.2851,81.52,70,8,1.97,clear sky
27,27,Vaini,TO,-21.2000,-175.2000,77.92,69,100,3.13,overcast clouds
29,29,Bubaque,GW,11.2833,-15.8333,76.55,78,13,13.09,few clouds

In [15]:
preferred_cities2 = preferred_cities.reset_index(drop=True)

NameError: name 'preferred_cities' is not defined

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0             207
City                   207
Country                207
Lat                    207
Lng                    207
Max Temp               207
Humidity               207
Cloudiness             207
Wind Speed             207
Current Description    207
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kapaa,US,80.58,broken clouds,22.0752,-159.3190,
4,Hobyo,SO,83.25,broken clouds,5.3505,48.5268,
10,Mabay,PH,84.15,moderate rain,6.0577,124.4666,
11,Buctzotz,MX,82.69,broken clouds,21.2000,-88.7833,
12,Rikitea,PF,75.33,moderate rain,-23.1203,-134.9692,
20,Namatanai,PG,85.69,overcast clouds,-3.6667,152.4333,
22,Butaritari,KI,81.52,broken clouds,3.0707,172.7902,
23,Bajil,YE,81.52,clear sky,15.0584,43.2851,
27,Vaini,TO,77.92,overcast clouds,-21.2000,-175.2000,
29,Bubaque,GW,76.55,few clouds,11.2833,-15.8333,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": G_API_Key
}


# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
 # 6c. Get latitude and longitude from DataFrame    lat = row["Lat"]
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"]=f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotels = requests.get(base_url, params=params).json()

    # 6e. Make request and retrieve the JSON data from the search. 
    #hotel_df = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kapaa,US,80.58,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
4,Hobyo,SO,83.25,broken clouds,5.3505,48.5268,Iftin hotel hobyo
10,Mabay,PH,84.15,moderate rain,6.0577,124.4666,Bautista Lodging House
11,Buctzotz,MX,82.69,broken clouds,21.2000,-88.7833,Buctoztz
12,Rikitea,PF,75.33,moderate rain,-23.1203,-134.9692,People ThankYou
20,Namatanai,PG,85.69,overcast clouds,-3.6667,152.4333,Seagulls Inn Namatani
22,Butaritari,KI,81.52,broken clouds,3.0707,172.7902,Isles Sunset Lodge
23,Bajil,YE,81.52,clear sky,15.0584,43.2851,فندق حضرموت
27,Vaini,TO,77.92,overcast clouds,-21.2000,-175.2000,Keleti Beach Resort
29,Bubaque,GW,76.55,few clouds,11.2833,-15.8333,"Casa Dora, Bubaque"

In [16]:
# 7. Drop the rows where there is no Hotel Name.

In [17]:
clean_hotel_df = hotel_df.replace(r'^\s*$', np.nan, regex=True)

In [20]:
clean_hotel_df = clean_hotel_df.dropna()

In [64]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [23]:
# 11a. Add a marker layer for each city to the map. 

locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Call the figure to plot the data.

fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))